version: '3.8'

services:
    postgres:
      container_name: postgres-db
      image: postgres:17-alpine

      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: rsreu

      restart: on-failure
      ports:
        - "5432:5432"
      volumes:
        - ../volumes/postgres:/var/lib/postgresql/data

# colima start --arch x86_64 --memory 4
# docker-compose up